[package]
name = "p8"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "1.0.0-alpha"
prometheus = "0.5"
lazy_static = "1.3"
evmap = "4.2.2"
coarsetime = "0.1"

[dependencies.add_metrics]
version = "0.1"
path = "./add_metrics" 
